services:
  - type: web
    name: igs-lanchonete-pro
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: AUTO_SETUP
        value: true
